<a href="https://colab.research.google.com/github/jooeeeiy/LinearAlgebra_2ndSem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
###Objective
1) Be familiar with the fundamental matrix operations.

2) Apply the operations to solve intermediate.

3) Apply matrix algebra in engineering solutions.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix  its transpose is denoted as . So for example:

$$
A=\begin{bmatrix} 1 & 2 & 5 \\ 5 & {-1} & 0\\ 0 & {-3} & 3\end{bmatrix} $$

$$ A^T=\begin{bmatrix} 1 & 5 & 0 \\ 2 & {-1} & {-3} \\ 5 & 0 & 3\end{bmatrix}
$$


np.transpose or T

In [ ]:
A= np.array ([
              [1,4,3],
              [3,30,1],
              [11, 25, 1]
])

In [ ]:
AT1= np.transpose(A)
AT1

array([[ 1,  3, 11],
       [ 4, 30, 25],
       [ 3,  1,  1]])

In [ ]:
AT2= A.T
AT2

array([[ 1,  3, 11],
       [ 4, 30, 25],
       [ 3,  1,  1]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B= np.array ([
              [10,-4],
              [36,0,],
              [3,6],
              [89,6],
              [10,19]
])
B.shape

(5, 2)

In [ ]:
np.transpose(B).shape

(2, 5)

In [ ]:
B.T. shape

(2, 5)

**Try to create your own matrix (you can try non-squares) to test transposition.**


In [ ]:
jozel= np.array ([
                  [0,11,25,1],
                  [1,30,3,0],
                  [6,2,9,3],
                  [10,17,85,89],
                  [1,2,3,4]
])
print('jozel matrix: \n',jozel, '\n')
print('Shape: ',jozel.shape)

jozel matrix: 
 [[ 0 11 25  1]
 [ 1 30  3  0]
 [ 6  2  9  3]
 [10 17 85 89]
 [ 1  2  3  4]] 

Shape:  (5, 4)


In [ ]:
print('Transpose Shape: ',np.transpose(jozel).shape)

Transpose Shape:  (4, 5)


In [ ]:
print('Transpose Shape: ',jozel.T.shape)


Transpose Shape:  (4, 5)


## Dot Product/Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$

 np.dot, np.matmul , @

In [ ]:
J= np.array([
             [1,2],
             [0,1],
             [8,9]
])
O= np.array ([
              [1,7,8,9,5,6,0],
              [2,5,6,7,8,9,1]
])

In [ ]:
np.array_equiv(J,O)

False

In [ ]:
J.dot(O)

array([[  5,  17,  20,  23,  21,  24,   2],
       [  2,   5,   6,   7,   8,   9,   1],
       [ 26, 101, 118, 135, 112, 129,   9]])

In [ ]:
J @ O

array([[  5,  17,  20,  23,  21,  24,   2],
       [  2,   5,   6,   7,   8,   9,   1],
       [ 26, 101, 118, 135, 112, 129,   9]])

In [ ]:
np.matmul(J,O)

array([[  5,  17,  20,  23,  21,  24,   2],
       [  2,   5,   6,   7,   8,   9,   1],
       [ 26, 101, 118, 135, 112, 129,   9]])

### RULE 1 The inner dimensions of the two matrices in question must be the same.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:


$$A = \begin{bmatrix}2 &4\\ 5 & {-2} \\0 & 1 \end{bmatrix}, B = \begin{bmatrix}1 & 1\\3 & 3 \\{-1} & {-2} \end{bmatrix}, C = \begin{bmatrix}0 & 1 & 1\\ 1 & 1& 2\end{bmatrix}$$


So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
U= np.array([
             [2,3,4],
             [5,6,7],
             [8,9,10]
])

N= np.array ([
             [8,9,7],
             [10,6,4],
             [8,2,9],
            [10,8,0]
])
R= np.array([
             [0,6,7,3],
             [0,1,2,9]
])

print('U:',U.shape)
print('N:',N.shape)
print('R: ',R.shape)

U: (3, 3)
N: (4, 3)
R:  (2, 4)


In [ ]:
N @ U

array([[117, 141, 165],
       [ 82, 102, 122],
       [ 98, 117, 136],
       [ 60,  78,  96]])

In [ ]:
R @ N

array([[146,  74,  87],
       [116,  82,  22]])

In [ ]:
U @ N

ValueError: ignored

In [ ]:
U @ N.T

array([[ 71,  54,  58,  44],
       [143, 114, 115,  98],
       [215, 174, 172, 152]])

### RULE 2:Dot Product has special properties
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$

In [ ]:
A=np.array([
            [1,2,3,4],
            [4,5,3,6],
            [1,0,1,9],
            [3,6,9,2]
])

B=np.array([
            [1,9,6,4],
            [8,2,5,2],
            [8,0,1,0],
            [1,0,2,0]
])

C=np.array([
            [6,7,4,5],
            [1,2,3,2],
            [0,0,6,8],
            [5,3,2,7]
])

In [ ]:
print('A @ B: \n',A @ B,'\n')
print('B @ A: \n',B @ A)

A @ B: 
 [[ 45  13  27   8]
 [ 74  46  64  26]
 [ 18   9  25   4]
 [125  39  61  24]] 

B @ A: 
 [[ 55  71  72 120]
 [ 27  38  53  93]
 [  9  16  25  41]
 [  3   2   5  22]]


In [ ]:
np.array_equiv(A @ B, B @ A)

False

In [ ]:
print('A @ (B @ C): \n',A @ (B @ C),'\n')
print('(A @ B) @ C: \n',(A @ B) @ C)

A @ (B @ C): 
 [[ 323  365  397  523]
 [ 620  688  870 1156]
 [ 137  156  257  336]
 [ 909 1025 1031 1359]] 

(A @ B) @ C: 
 [[ 323  365  397  523]
 [ 620  688  870 1156]
 [ 137  156  257  336]
 [ 909 1025 1031 1359]]


In [ ]:
np.array_equiv(A @ (B @ C), (A @ B) @ C)

True

In [ ]:
print('A @ (B + C): \n',A @ (B + C),'\n')
print('(A @ B) + (A @ C): \n',(A @ B) + (A @ C))

A @ (B + C): 
 [[ 73  36  63  69]
 [133 102 125 122]
 [ 69  43  53  80]
 [159  78 149 137]] 

(A @ B) + (A @ C): 
 [[ 73  36  63  69]
 [133 102 125 122]
 [ 69  43  53  80]
 [159  78 149 137]]


In [ ]:
np.array_equiv(A @ (B + C), (A @ B) + (A @ C))

True

In [ ]:
print('(B + C) @ A: \n',(B + C)@ A,'\n')
print('(B @ A) + (C @ A): \n',(B @ A) + (C @ A))

(B + C) @ A: 
 [[108 148 160 232]
 [ 45  62  83 140]
 [ 39  64 103 111]
 [ 43  69  94  92]] 

(B @ A) + (C @ A): 
 [[108 148 160 232]
 [ 45  62  83 140]
 [ 39  64 103 111]
 [ 43  69  94  92]]


In [ ]:
np.array_equiv((B + C) @ A, (B @ A) + (C @ A))

True

In [ ]:
A@np.eye(4)

array([[1., 2., 3., 4.],
       [4., 5., 3., 6.],
       [1., 0., 1., 9.],
       [3., 6., 9., 2.]])

In [ ]:
np.array_equiv(A, A@np.eye(4))

True

In [ ]:
A @ np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equiv(A @ np.zeros((4,4)),np.zeros((4,4)))

True

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
j_mat = np.zeros(A.shape)
j_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
o_dot_z = A.dot(np.zeros(A.shape))
o_dot_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equal(o_dot_z,j_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(o_dot_z,null)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


True

##Determinant (only on square matrix)
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
J= np.array ([
              [1,2],
              [6,5],
])
np.linalg.det(J)

-6.999999999999999

In [ ]:
 ## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

V= np.array ([
              [4,8],
              [3,7]
])

np.linalg.det(V)

4.0

##Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
joey = np.array([
                 [1,4,3],
                 [8,7,7],
                 [1,5,4]
])

np.array(joey @ np.linalg.inv(joey), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
jozie= np.array ([
                  [25,20,30,65,98,9],
                  [1,2,3,4,5,6],
                  [10, 11,23,78,7,8],
                  [19,53,86,72,6,32],
                  [5,5,5,5,5,5],
                  [9,26,74,25,26,25]
])
jozie_inv = np.linalg.inv(jozie)
np.array(jozie @ jozie_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
Q= np.array([
             [1,2,3],
             [3,5,4],
             [7,2,1]
])
R=np.linalg.inv(Q)
R

array([[ 0.075, -0.1  ,  0.175],
       [-0.625,  0.5  , -0.125],
       [ 0.725, -0.3  ,  0.025]])

In [ ]:
Q@R

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.77555756e-17],
       [ 0.00000000e+00,  1.66533454e-16,  1.00000000e+00]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

# **Activity**

## Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [12,54,64],
    [46,78,46],
    [8,18,23]
])
B = np.array([
    [65,1213,643],
    [124,165,965],
    [313,343,383]
])
C = np.array([
    [131,313,10],
    [660,451,134],
    [112,302,112]
])

In [ ]:
A @ B

array([[ 27508,  45418,  84338],
       [ 27060,  84446, 122466],
       [  9951,  20563,  31323]])

In [ ]:
B @ A

array([[ 61722, 109698,  74747],
       [ 16798,  36936,  37721],
       [ 22598,  50550,  44619]])

In [ ]:
np.array_equiv(A @ B, B @ A)

False

In [ ]:
A @ (B@C)

array([[43025284, 54563598, 15806948],
       [72995412, 83539658, 25302556],
       [18383337, 21848122,  6363128]])

In [ ]:
(A@B)@C

array([[43025284, 54563598, 15806948],
       [72995412, 83539658, 25302556],
       [18383337, 21848122,  6363128]])

In [ ]:
np.array_equiv(A@(B@C),(A@B)@C)

True

In [ ]:
A@(B+C)

array([[ 71888,  92856,  98862],
       [ 89718, 147914, 138530],
       [ 25455,  38131,  36391]])

In [ ]:
A@B + A@C

array([[ 71888,  92856,  98862],
       [ 89718, 147914, 138530],
       [ 25455,  38131,  36391]])

In [ ]:
np.array_equiv(A@(B+C),A@B + A@C)

True

In [ ]:
(B+C)@A

array([[ 77772, 141366,  97759],
       [ 46536, 110166, 103789],
       [ 38730,  82170,  68255]])

In [ ]:
B@A + C@A

array([[ 77772, 141366,  97759],
       [ 46536, 110166, 103789],
       [ 38730,  82170,  68255]])

In [ ]:
np.array_equiv((B+C)@A,B@A + C@A)

True

In [ ]:
A@np.eye(3)

array([[12., 54., 64.],
       [46., 78., 46.],
       [ 8., 18., 23.]])

In [ ]:
np.array_equiv(A, A@np.eye(3))

True

In [ ]:
A@np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equiv(A@np.zeros((3,3)),np.zeros((3,3)))

True

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#**Conclusion**

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?".