<a href="https://colab.research.google.com/github/jooeeeiy/LinearAlgebra_2ndSem/blob/main/Matrix_Arriola_Valenzuela.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Activity

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:


1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function area

import numpy as np

In [ ]:
## Matrix declarations

def mat_desc(matrix):
  if matrix.size >0:
    is_square= True if matrix.shape[0] == matrix.shape[1] else False
    print (f'{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare:\t{is_square}\nMatrix is not Null')
  else:
    print ('Matrix is Null')

In [ ]:
## Test Areas

mat_1= np.ones((6,6,))

print('Matrix 1:')
mat_desc(mat_1)

result = np.all((np.identity(6)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_1 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_1 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

Matrix 1:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Shape:	(6, 6)
Rank:	2
Square:	True
Matrix is not Null
Not an Identity Matrix
Ones Matrix
Contains non-zero element


In [ ]:
## Test Areas

mat_2= np.zeros((5,10))
print('Matrix 2:')
mat_desc(mat_2)

result = np.all((np.identity(5)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_2 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_2 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

Matrix 2:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Shape:	(5, 10)
Rank:	2
Square:	False
Matrix is not Null
Not an Identity Matrix
Contains non-one element
Zero Matrix


In [ ]:
## Test Areas

mat_3= np.array ([   
                  [13,67,89,90,67,55,99],
                  [55,78,6,33,900,0,3],
                  [21,34,5,88,93,87,54],
                  [27,76,98,0,96,26,37],
                  [4,5,3,9,2,8,9],
                  [25,30,11,3,1,27,8],
                  [13,69,0,65,7,8,45]         
])
print('Matrix 3:')
mat_desc(mat_3)

result = np.all((np.identity(7)))
if result:
  print('Identity Matrix')
else:
  print('Not an Identity Matrix')

result = np.all((mat_3 == 1))
if result:
  print('Ones Matrix')
else:
  print('Contains non-one element')

result = np.all((mat_3 == 0))
if result:
  print('Zero Matrix')
else:
  print('Contains non-zero element')

##Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the difference of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than (3x3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_operations(matrix):
  print (f'{matrix}')

In [ ]:
R4 = int(input('Enter the number of rows: '))
C4 = int(input('Enter the number of columns: '))

print('\nEnter',R4*C4,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE:Your first',C4,' number/s would be the first row):')
m4 = list(map(int, input().split()))
mat_4 = np.array(m4).reshape(R4, C4)
print('\nMatrix 4 is:')
mat_operations(mat_4)

print('----------------------------------------------')

R5 = int(input('Enter the number of rows: '))
C5 = int(input('Enter the number of columns: '))

print('\nEnter',R5*C5,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C5,' number/s would be the first row):')
m5 = list(map(int, input().split()))
mat_5 = np.array(m5).reshape(R5, C5)
print('\nMatrix 5 is:')
mat_operations(mat_5)

print('----------------------------------------------')

R6 = int(input('Enter the number of rows: '))
C6 = int(input('Enter the number of columns: '))

print('\nEnter',R6*C6,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C6,' number/s would be the first row):')
m6 = list(map(int, input().split()))
mat_6 = np.array(m6).reshape(R6, C6)
print('\nMatrix 6 is:')
mat_operations(mat_6)

print('----------------------------------------------')

R7 = int(input('Enter the number of rows: '))
C7 = int(input('Enter the number of columns: '))

print('\nEnter',R7*C7,'values for Matrix 1\n\t(NOTE: Use space for separating the numbers)\n\t(NOTE: Your first',C7,' number/s would be the first row):')
m7 = list(map(int, input().split()))
mat_7 = np.array(m7).reshape(R7, C7)
print('\nMatrix 7 is:')
mat_operations(mat_7)

Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE:Your first 3  number/s would be the first row):
1 2 3 4 5 6 7 8 9

Matrix 4 is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------
Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE: Your first 3  number/s would be the first row):
9 8 7 6 5 4 3 2 1

Matrix 5 is:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
----------------------------------------------
Enter the number of rows: 3
Enter the number of columns: 3

Enter 9 values for Matrix 1
	(NOTE: Use space for separating the numbers)
	(NOTE: Your first 3  number/s would be the first row):
-7 -4 -1 8 5 2 -9 6 -3

Matrix 6 is:
[[-7 -4 -1]
 [ 8  5  2]
 [-9  6 -3]]
----------------------------------------------
Enter the number of rows: 4
Enter the number of columns: 4

Enter 16 values for Matrix 1
	(NOTE:

In [ ]:
#Determines if the matrices are viable for operation and returns your own error message if they are not viable.
print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 5:')
mat_operations(mat_5)
result1 = (mat_4.shape == mat_5.shape)
if result1:
  print('\nMatrix 4 and Matrix 5 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 5 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 6:')
mat_operations(mat_6)
result2 = (mat_4.shape == mat_6.shape)
if result2:
  print('\nMatrix 4 and Matrix 6 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 6 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 5:')
mat_operations(mat_5)
print('\nMatrix 6:')
mat_operations(mat_6) 
result3 = (mat_5.shape == mat_6.shape)
if result3:
  print('\nMatrix 5 and Matrix 6 are Viable for Operation')
else:
  print('\nMatrix 5 and Matrix 6 are Not Viable for Operation')

print('\n------------------------------------------------------')

print('Matrix 4:')
mat_operations(mat_4)
print('\nMatrix 7:')
mat_operations(mat_7) 
result4 = (mat_4.shape == mat_7.shape)
if result4:
  print('\nMatrix 4 and Matrix 7 are Viable for Operation')
else:
  print('\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 5:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 4 and Matrix 5 are Viable for Operation

------------------------------------------------------
Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 6:
[[-7 -4 -1]
 [ 8  5  2]
 [-9  6 -3]]

Matrix 4 and Matrix 6 are Viable for Operation

------------------------------------------------------
Matrix 5:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 6:
[[-7 -4 -1]
 [ 8  5  2]
 [-9  6 -3]]

Matrix 5 and Matrix 6 are Viable for Operation

------------------------------------------------------
Matrix 4:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 7:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 -9 -8 -7]
 [-6 -5 -4 -2]]

Matrix 4 and Matrix 7 are Not Viable for Operation


In [ ]:
#Sum of the matrices

if result1:
  sum_1= mat_4 + mat_5
  print('Sum result 1:\n',sum_1)
else:
  print('Matrix 4 and Matrix 5 are Not Viable for Operation')

if result3:
  sum_2= mat_5 + mat_6
  print('\n\nSum result 2:\n',sum_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

if result4:
  sum_4= mat_4 + mat_7
  print('\n\nSum result 3:\n',sum_4)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Sum result 1:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


Sum result 2:
 [[ 2  4  6]
 [14 10  6]
 [-6  8 -2]]


Matrix 4 and Matrix 7 are Not Viable for Operation


In [ ]:
#Difference of the matrices

if result2:
  d_1= mat_4 - mat_6
  print('Difference result 1:\n',d_1)
else:
  print('Matrix 4 and Matrix 6 are Not Viable for Operation')

if result4:
  sum_4= mat_4 - mat_7
  print('\n\nDifference result 2:\n',sum_4)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

if result3:
  d_2= mat_5 - mat_6
  print('\n\nDifference result 3:\n',d_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

Difference result 1:
 [[ 8  6  4]
 [-4  0  4]
 [16  2 12]]


Matrix 4 and Matrix 7 are Not Viable for Operation


Difference result 3:
 [[16 12  8]
 [-2  0  2]
 [12 -4  4]]


In [ ]:
#Element-wise multiplication of the matrices

if result1:
  m_1= mat_4 * mat_5
  print('Product result 1:\n',m_1)
else:
  print('Matrix 4 and Matrix 5 are Not Viable for Operation')

if result3:
  m_2= mat_5 * mat_6
  print('\n\nProduct result 2:\n',m_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

if result4:
  m_3= mat_4 * mat_7
  print('\n\nProduct result 3:\n',m_3)
else:
  print('\n\nMatrix 4 and Matrix 7 are Not Viable for Operation')

Product result 1:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Product result 2:
 [[-63 -32  -7]
 [ 48  25   8]
 [-27  12  -3]]


Matrix 4 and Matrix 7 are Not Viable for Operation


In [ ]:
#Element-wise division of the matrices

if result4:
  dv_3= mat_4 / mat_7
  print('Quotient result 1:\n',dv_3)
else:
  print('Matrix 4 and Matrix 7 are Not Viable for Operation')

if result2:
  dv_1= mat_4 / mat_6
  print('\n\nQuotient result 2:\n',dv_1)
else:
  print('\n\nMatrix 4 and Matrix 6 are Not Viable for Operation')

if result3:
  dv_2= mat_5 / mat_6
  print('\n\nQuotient result 3:\n',dv_2)
else:
  print('\n\nMatrix 5 and Matrix 6 are Not Viable for Operation')

Matrix 4 and Matrix 7 are Not Viable for Operation


Quotient result 2:
 [[-0.14285714 -0.5        -3.        ]
 [ 0.5         1.          3.        ]
 [-0.77777778  1.33333333 -3.        ]]


Quotient result 3:
 [[-1.28571429 -2.         -7.        ]
 [ 0.75        1.          2.        ]
 [-0.33333333  0.33333333 -0.33333333]]


##Conclusion


> Matrix is a method or technique that is widely used in mathematics and physics to easier solve linear equations.[9] In this laboratory, the students gained knowledge about how the matrix can be applied to programming. They have learned that matrices can be: converted into a linear combination or LaTex Markdown, classified into zero matrix, identity matrix or ones matrix, and solved with different operations such as addition, subtraction, multiplication, and division. With the help of the functions and variables like NumPy or np, and “describe_mat(),” “mat_desc(),” & “mat_operations(),” the students were able to run programs that prints matrices and define them. 


> The world today adapted to the advancement of technology which increased human reliability, especially in the future. The current generation is welcomed in the world wherein they must be skilled and knowledgeable enough on technology to survive and work as a person. [10] This technology nowadays is composed of endless codes to make something work, including matrix. Therefore when technology has an emerging problem, it is only through itself also that it can be solved. One application that matrix can be used as a solution would be on Wireless Communication because it is a sensor that detects problems on wireless communication and its signal estimation. Matrices are said to be used as wireless signals(sensor arrays) in which the information is extracted and operated. The sensor arrays detect and locate the problem radiating provenance by the temporal and spatial information collected from the sensors. The matrices can help the process of illustrating digital images.[9]